### ISSUE TITLE
Spatial Audio On Moving character

### ISSUE THREAD

**Issue by WalidCHEKKOURI** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#49]
I explored the BP sample of spatial voice, I'm trying to have a 3D immersive surround sound for moving players in the 3D space, however  the spatial example I explored based on my knowledge seems to not be very clear as it uses the vectors (0,1,0) for moving right and (0,-1,0 ) for moving left, I tried plugging the player's actual location to the MakeRemoteVoicePositionInfo but it didn't work, also how can I change the attenuation distance and other parameters too? If you can show a more intuitive example it would be better.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/11277981/197357400-8c544122-80fc-41f6-bcef-215115f356f9.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/11277981/197357359-780d1985-a5da-4a4a-b8a9-1d5ba4469659.png">

Thanks

**Comment by oneSitDown** [comment]
You can store the userid of the remote user when he joins the room and then update his location. Currently just a simple demo. You can see that I have a small number of examples now. Our goal now is to complete more examples, rather than perfect a certain example. If you want faster support, you can contact our SA. We will put it on the agenda as soon as possible.
