### ISSUE TITLE
Unable to build plugin for Unreal 5.2.1

### ISSUE THREAD

**Issue by Raibatsu** [AgoraIO-Extensions/Agora-Unreal-RTC-SDK#90]
Hi, I am a newb so apologies in advance. I am trying to run Agora plugin for Unreal Editor 5.2.1, but it isn't being built. I am using BuildTools' RunUAT. 
I have attached the log, I hope that helps. 

Cheers, and looking forward to finding a fix! Please let me know if you need anything else.
[agora unreal 5.2 build log.txt](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/files/12523237/agora.unreal.5.2.build.log.txt)

**Comment by WinterPu** [comment]
These errors are fixed here: [https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/dev/4.2.1/](https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/blob/dev/4.2.1/)
You can replace the entire AgoraPlugin/Source/AgoraPlugin folder and recompile again.
 Please let me know if any other errors occur.

**Comment by WinterPu** [comment]
Hi, if it's not necessary to build the plugin in this manner, you can simply package the project directly. One of the errors in your log could be fixed with this commit https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/commit/afbd586465fb07070b94c1af79e569b2cde728f4 As for the other errors, it seems they might be related to changes in the building environment due to the building order. I will dig into this problem later. If you need to build this plugin in this way, you could supplement any missing includes to resolve the error for now.

**Comment by WinterPu** [comment]
This issue should be fixed in this commit， https://github.com/AgoraIO-Extensions/Agora-Unreal-RTC-SDK/commit/b99076fd79cbca9c63a32c0f4ac08391990d1d2a . You could check it.

**Comment by WinterPu** [comment]
It compiles the plugin independently, so it lacks correctly including the header file windows.h. You could check UE's doc here.  https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/BuildTools/UnrealBuildTool/ThirdPartyLibraries/
